# app/nodes/normalize.py
from app.state import JournalState
from datetime import datetime, timedelta, timezone
import os
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

load_dotenv()
os.environ["GOOGLE_API_KEY"] = os.getenv("GEMINI_API_KEY")
model = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.1)


def extract_text_from_response(response):
    content = response.content
    if isinstance(content, list):
        content = "".join(
            block["text"] if isinstance(block, dict) else str(block)
            for block in content
        )
    return content.strip()


def resolve_user_timezone(user_timezone: str):
    timezone_name = (user_timezone or "UTC").strip() or "UTC"
    try:
        return ZoneInfo(timezone_name)
    except Exception:
        try:
            return ZoneInfo("UTC")
        except Exception:
            return timezone.utc


def generate_calendar_reference(today_date) -> str:
    anchor_start = today_date - timedelta(weeks=4)
    anchor_end = today_date + timedelta(weeks=8)

    start_of_first_week = anchor_start - timedelta(days=anchor_start.weekday())
    end_of_last_week = anchor_end + timedelta(days=(6 - anchor_end.weekday()))

    weekday_labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    lines = []
    current_week_start = start_of_first_week

    while current_week_start <= end_of_last_week:
        week_days = [
            current_week_start + timedelta(days=offset)
            for offset in range(7)
        ]
        day_entries = ", ".join(
            f"{label}={day.isoformat()}"
            for label, day in zip(weekday_labels, week_days)
        )
        lines.append(
            f"Week of {current_week_start.strftime('%b')} {current_week_start.day}: {day_entries}"
        )
        current_week_start += timedelta(weeks=1)

    return "\n".join(lines)


def build_normalize_prompt(text: str, current_dt: datetime) -> str:
    today = current_dt.strftime("%Y-%m-%d")
    day_name = current_dt.strftime("%A")
    today_date = current_dt.date()
    this_week_monday = today_date - timedelta(days=today_date.weekday())
    next_week_monday = this_week_monday + timedelta(weeks=1)
    prev_week_monday = this_week_monday - timedelta(weeks=1)
    calendar_reference = generate_calendar_reference(today_date)

    return f'''You are a text normalization engine.

CRITICAL RULE: You MUST use the calendar reference below to look up dates. Do NOT calculate or compute dates yourself. The calendar is generated by a computer and is guaranteed correct. Your math is not.
CRITICAL RULE: If the original text contains no relative date phrases (like "tomorrow", "next Monday", "by Friday", "last week", "in 3 days", etc.), do NOT add any dates. Only replace dates that clearly exist in the original text. When in doubt, do NOT add a date.

---

Today is {day_name}, {today}.

WEEK ANCHORS — use these to find the correct calendar row:
- TODAY ({today}) is in the row starting with: "Week of {this_week_monday.strftime("%b")} {this_week_monday.day}:"
- "next week" row starts with: "Week of {next_week_monday.strftime("%b")} {next_week_monday.day}:"
- "last week" row starts with: "Week of {prev_week_monday.strftime("%b")} {prev_week_monday.day}:"

HOW TO USE THE CALENDAR FOR "next [weekday]" AND "last [weekday]":
- "next Monday" → go to the "next week" row above, find Mon=YYYY-MM-DD, copy that date.
- "next Tuesday" → go to the "next week" row above, find Tue=YYYY-MM-DD, copy that date.
- "next [any weekday]" → always use the "next week" row, never the current week row.
- "last [weekday]" → means THE MOST RECENT occurrence of that weekday BEFORE today, NOT necessarily last week's row.
  Rule: weekday order is Mon=1, Tue=2, Wed=3, Thu=4, Fri=5, Sat=6, Sun=7.
  If the target weekday number < today's weekday number: the most recent occurrence is IN THIS WEEK's row (it already passed this week). Use today's row.
  If the target weekday number >= today's weekday number: the most recent occurrence was last week. Use the "last week" row.
  Example: today is Thursday (4). "Last Tuesday" → Tuesday=2, which is less than 4, so Tuesday already passed THIS week → use today's row → find Tue= in "Week of {this_week_monday.strftime("%b")} {this_week_monday.day}:" row.
  Example: today is Thursday (4). "Last Friday" → Friday=5, which is >= 4, so Friday has NOT passed this week → use last week's row → find Fri= in "Week of {prev_week_monday.strftime("%b")} {prev_week_monday.day}:" row.

HOW TO RESOLVE "end of next month":
- "next month" = the month AFTER the current month. Current month is {current_dt.strftime("%B %Y")}.
- "end of next month" = the last day of that next month. Look up the last day of that month in the calendar.
- Example: if today is in April 2026, "end of next month" = last day of May 2026 = 2026-05-31. Find the row containing "May 31" in the calendar and copy that date.

Calendar reference (use this to look up every date — do not compute):
IMPORTANT: Do NOT calculate dates yourself. Find the exact row using the WEEK ANCHORS above, then copy the date from the correct column.

{calendar_reference}

---

How to resolve relative dates (follow these steps in order):

Step 1: Identify any relative date phrase in the text (e.g., "next Monday", "by Friday", "tomorrow", "last Tuesday", "in 2 weeks", "nxt monday", "tmrw").
Step 2: If NO relative date phrase exists in the original text, skip date conversion entirely. Do not invent or add any dates.
Step 3: For each relative date phrase found, use the WEEK ANCHORS and HOW TO USE THE CALENDAR rules above to determine which exact calendar row to look in.
Step 4: Find that specific row in the calendar reference. Copy the exact YYYY-MM-DD date from the correct column.
Step 5: Replace the relative phrase in the text with the looked-up date. Do not compute the date yourself.

---

Text cleanup rules:

- Fix obvious typos, grammar, and slang while preserving meaning (e.g., "gonna" → "going to", "gotta" → "have to", "abt" → "about", "tmrw" → the resolved date, "nxt" → "next").
- Preserve ALL proper nouns, project names, people's names, nicknames, and specific terms exactly as written, even if they look like typos (e.g., "ProjectX", "MindGraph", "Sagarika", "Rahul").
- Do NOT summarize, shorten, or remove any content from the original text.
- Do NOT add new content, opinions, or information that was not in the original text.

---

Output format:

Return ONLY the cleaned text. Nothing else. No explanations, no headers, no labels, no markdown.

---

Original Text: {text}
'''


async def normalize(state: JournalState) -> dict:
    text = state["raw_text"]
    user_timezone = state.get("user_timezone", "UTC")
    current_dt = datetime.now(resolve_user_timezone(user_timezone))
    prompt = build_normalize_prompt(text, current_dt)

    response = await model.ainvoke(prompt)
    cleaned = extract_text_from_response(response)

    return {"cleaned_text": cleaned}
